### ISSUE TITLE
Environment Error: inplace_abn

### ISSUE THREAD

**Issue by HyperbolicCurve** [dragonfly606/MonoCD#6]
Hi, when I was trying pip install -r requirements.txt,it came out with:
Error: Failed building wheel for inplace_abn.
Error: Error: Failed to build installable wheels for some pyproject.toml based projects(inplace_abn).
I wonder how to fix the problem.
nvcc version: 11.3 
![image](https://github.com/user-attachments/assets/18621f27-d0b6-4ef1-ba05-0eaf1c65aafb)

**Comment by dragonfly606** [comment]
@HyperbolicCurve Sorry I'm late. I used to solve this by using `conda install inplace_abn`. If it doesn't work, you need to make sure your version of nvcc is the same as cudatoolkit. Because the installation of inplace_abn involves compiling. You don't necessarily have to lower your nvcc version, you can use cudatoolkit 11.3 and the corresponding higher level pytorch version
